apiVersion: v2
appVersion: 25.4.0-142
dependencies:
- condition: global.cs-secrets.enabled
  name: cs-secrets
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.db.enabled
  name: db
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "17.2"
- condition: global.content-server.enabled
  name: cs-logging-configMap
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.docbroker.enabled
  name: docbroker
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.content-server.enabled
  name: content-server
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.content-server.enabled
  name: dctm-ingress
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.multiIngress
  name: vpningress
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.multiIngress
  name: d2publicingress
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.content-server.enabled
  name: cs-dfc-properties
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.dtrbase.enabled
  name: dtrbase
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.dctm-rest.enabled
  name: dctm-rest
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.dctm-cmis.enabled
  name: dctm-cmis
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.dctm-workflow-designer.enabled
  name: dctm-workflow-designer
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.contentconnect.enabled
  name: contentconnect
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.da.enabled
  name: da
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.dfs.enabled
  name: dfs
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.records.enabled
  name: records
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.rqm.enabled
  name: rqm
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.dctm-dcc.enabled
  name: dctm-dcc
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.otds.enabled
  name: otds
  repository: https://artifactory.otxlab.net/artifactory/plteng-otds-helm-rel
  version: 25.4.0
- condition: global.d2config.enabled
  name: d2config
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.d2classic.enabled
  name: d2classic
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.d2smartview.enabled
  name: d2smartview
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.d2rest.enabled
  name: d2rest
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.adminconsole.enabled
  name: adminconsole
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.appworks-gateway.enabled
  name: appworks-gateway
  repository: https://artifactory.otxlab.net/artifactory/plteng-otawg-helm-rel-local
  version: 25.4.0
- condition: global.xPlore-OneD.enabled
  name: xPlore-OneD
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: 22.1.14
- condition: global.otiv.enabled
  name: otiv
  repository: https://artifactory.otxlab.net/artifactory/cs-vandt-helm-pre
  version: 25.4.0
- condition: global.smartviewm365.enabled
  name: smartviewm365
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.notificationservice.enabled
  name: notificationservice
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.oesconnector.enabled
  name: oesconnector
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.bps.enabled
  name: bps
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.xda.enabled
  name: xda
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.documentum-search.enabled
  name: documentum-search
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.amq.enabled
  name: amq
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: 2.41.0-10
- condition: global.dctm-dcis.enabled
  name: dctm-dcis
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.ijms.enabled
  name: ijms
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.ao-installer.enabled
  name: ao-installer
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.lss.enabled
  name: lss
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: 25.4.0
- condition: global.dctm-dms.enabled
  name: dctm-dms
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.dctm-assap.enabled
  name: dctm-assap
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.dctm-assap-ilm.enabled
  name: dctm-assap-ilm
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
- condition: global.dctm-cssap.enabled
  name: dctm-cssap
  repository: https://artifactory.otxlab.net/artifactory/cs-dctm-helm-rel
  version: "25.4"
description: Documentum Helm chart for Kubernetes
name: documentum
version: "25.4"
